services:
  # Database service
  postgres:
    image: postgres:15-alpine
    container_name: ai-hedge-fund-db
    environment:
      POSTGRES_USER: hedge_fund
      POSTGRES_PASSWORD: hedge_fund_password
      POSTGRES_DB: hedge_fund_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hedge_fund"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ai-hedge-fund-backend
    environment:
      - DATABASE_URL=postgresql://hedge_fund:hedge_fund_password@postgres:5432/hedge_fund_db
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./app/backend:/app/app/backend
      - ./.env:/app/.env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn app.backend.main:app --host 0.0.0.0 --port 8000 --reload
      "

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ai-hedge-fund-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  # Ollama service for local LLMs
  ollama:
    image: ollama/ollama:latest
    container_name: ai-hedge-fund-ollama
    profiles:
      - with-ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # CLI service for running hedge fund directly
  hedge-fund-cli:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ai-hedge-fund-cli
    profiles:
      - cli
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - DATABASE_URL=postgresql://hedge_fund:hedge_fund_password@postgres:5432/hedge_fund_db
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    command: python src/main.py --ticker AAPL,MSFT,NVDA
    depends_on:
      postgres:
        condition: service_healthy
    stdin_open: true
    tty: true

  # Backtester service
  backtester:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ai-hedge-fund-backtester
    profiles:
      - backtester
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - DATABASE_URL=postgresql://hedge_fund:hedge_fund_password@postgres:5432/hedge_fund_db
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    command: python src/backtester.py --ticker AAPL,MSFT,NVDA
    depends_on:
      postgres:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  ollama_data:

networks:
  default:
    name: ai-hedge-fund-network